name: Simple Chat API Dev Deployment
on:
  push:
    branches:
      - develop

env:
  SIMPLE_CHAT_API_IMAGE_REPO: ${{ secrets.IMAGE_REPO }}
  IMAGE_TAG: 0.0.1

jobs:
  ci:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download env file from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        aws_access_key_id: ${{ secrets.AWS_S3_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        source: ${{ secrets.SIMPLE_CHAT_API_ENV_FILE }}
        destination: './simple-chat-api/.env'

    - name: Configure AWS credentials for ECR
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t ${{ secrets.IMAGE_REPO }}:${{ env.IMAGE_TAG }} ./simple-chat-api
        docker push ${{ secrets.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

    - name: Deployment to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_SSH_HOST }}
        port: ${{ secrets.AWS_EC2_SSH_PORT }}
        username: ${{ secrets.AWS_EC2_SSH_USER }}
        password: ${{ secrets.AWS_EC2_SSH_PW }}

        script: |
          cd simple-chat-api && \
          docker pull ${{ secrets.IMAGE_REPO }}:${{ env.IMAGE_TAG }} && \
          docker rm -f simple-chat-api || true && \
          docker run -d -p 5000:5000 simple-chat-api:0.0.1 -n simple-chat-api
